version: "3.7"
services:
  #outro container --- backend
  springweb:
    container_name: dockerback
    build: . #preciso do Dockerfile para gerar a imagem
    ports:
      - "8080:8080"
    networks:
      - servers
    environment:
      SPRING_PROFILES_ACTIVE: aws

networks:
  servers:
    driver: bridge