- hosts: all
  become: yes #vira sudo sempre que precisar
  tasks:
  - name: alterando nome dos hosts
    hostname:
      name: "{{ new_hostname }}"
  # 1
  - name: instalar dependencias do docker e java para compilar
    apt: # apt-get install apt-transport-https 
      name: "{{item}}"
      state: present 
      update_cache: yes
    loop:
      - apt-transport-https #0
      - ca-certificates #1
      - curl
      - gnupg-agent
      - software-properties-common
      - openjdk-17-jdk
      - maven  
  # 2
  - name: adicionar chave GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  # 3
  - name: adicionar repositório d0 instalador do docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  # 4
  - name: instala docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
  # 5
  - name: instalar python e pip ansible precisa para poder iniciar o Docker, executar
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - python3
      - pip
  # 6
  - name: Instalar recurso docker que o ansible precisa
    pip:
      name: docker
  # Fim

  handlers:
  # 1
    - name: reiniciar docker
      service: 
        name: docker 
        state: restarted
  # 2
    - name: remover pasta tizu da home
      become: true
      shell:
        cmd: rm -rf /home/ubuntu/tizu
  # Fim

- hosts: backend
  become: yes
  tasks:
  # 1
  - name: Clonando o Repositorio do Projeto Ecommerce em JAVA
    ansible.builtin.git:
      # o repositório que vamos clonar
      repo: https://github.com/cypherbold/tizu
      # onde vamos clonar
      dest: /home/ubuntu/tizu
      # qual é a branch que vamos clonar
      version: main
      # aqui estopu dizendo que quero seja feito update sempre que rodar a tarefa
      update: yes
      # force pq eu quero, baixa e pronto. eu mandei.
      force: yes
  # 2
  - name: mvn install
    shell:
      cmd: "sudo mvn install"
      chdir: /home/ubuntu/tizu
  # 3
  - name: Rodando docker-compose mysql
    become: true
    shell:
      cmd: "docker-compose -f docker-compose-mysql.yml up -d"
      chdir: /home/ubuntu/tizu
  # Fim